query getAuthorsWithTotals {
    queryAuthorsContentsWithTotal {
        total
        items {
            id
            flatData {
                name
            }
            referencingPostsContentsWithTotal {
                total
            }
		}
    }
}